### ISSUE TITLE
Some errors while importing to project

### ISSUE THREAD

**Issue by chwastek** [rnystrom/RNBlurModalView#10] opened 2013-02-26 12:00 UTC
Hi there,
I just tried to put your RNBlurModalView into my project, so I can play a bit with it. Unfortunatelly it produced error:
1) in RNBlurModalView.m
dispatch_once(&once, ^{
        closeButtonImage = [self closeButtonImage];
    });
Receiver type 'RNCloseButton' for instance message does not declare a method with selector 'closeButtonImage'.
kind regards
F

**Comment by rnystrom** [comment] 2013-02-27 16:02
Closing this for now. I'd remove the project and re-add it. It looks like something got skipped or deleted by accident as this method is definitely included. Some steps to reproduce would be great.

https://github.com/rnystrom/RNBlurModalView/blob/master/RNBlurModalView.m#L515

**Closed as completed by rnystrom** 2013-02-27 16:02 UTC
